redis:
  image: redis
  ports:
    - 6379:6379
db:
  image: orchardup/postgresql
  ports:
    - 5432:5432
web:
  build: ./api
  command: python ./api/run.py runserver -h 0.0.0.0 -p 5000
  volumes:
    - .:/code
    - ~/.config/gcloud:/root/.config/gcloud
  ports:
    - 5000:5000
  links:
    - db
  environment:
    DEBUG: "True"
    SECRET_KEY: __filler__
    SMTP_USERNAME: __filler__
    SMTP_PASSWORD: __filler__
    SMTP_SENDER_NAME: Deep Learning Indaba
    SMTP_SENDER_EMAIL: baobab@deeplearningindaba.com
    SMTP_HOST: __filler__
    SMTP_PORT: 587
    GCP_CLIENT_ID: 114966260410024802375
    GCP_CLIENT_EMAIL: baobab-service@baobab.iam.gserviceaccount.com
    GCP_PRIVATE_KEY_ID: 2dafcfc720fb7b5d8d9248c58f574621a6861655
    GCP_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC2+BBQlzjxP4dx\nFfWniQ1ex5+3BSWg7w0gURMr5wZ8GDPgt4vNflE2LTOzwEvZ0LAqg3U8pmD16roJ\nZqh7KIjAHS7AgtEAALoTRDZ5OuNKwFw5EB3xrhHqlX03Qjzi0BHRh/52Bqs/SNfJ\npmuOXVcETQO/3CJCl2U4I1KWeTARKx/Eb+gKqH969Ez/r4o1RBanb45eGenm4IT5\nP3bvWyxZHNaK1Z9hWg4PK6bYwWE89dBWicE33Ng0tauKkmLkI2mweNjbBoR09Q6R\nxEZx0JcqHhIdQq3V8f6+tcIZBDU0YUpcLBDWhdogGZ0C3aHsSM5ilp4zS96EGxZG\njv16S38LAgMBAAECggEAE0WnukVjaw3M/11XxbDK5rvSF94D66KiWFAR2+L2rOWD\nuVy77gYrGbDDLGDJ3IR9ucyk8aF4vw5dUBYvEuHfHZU1UnO0/fIVp2fc8QIB5OLE\nFAKdlNJH8tSSHtrsPNu7tL1FUTs8mGrcx9GurI0qWDqgdXoDZc46jCI0VcMoC/a4\nRdPDabUX+n01locjBSRM92AAqFsPiWR8BH2qiJ1gpEL+O5k1q8vpfaahNXUKb1C3\nizemWXUmpci070ptyaJ8PyIz0WLwO+lxvPfzcdeg6lQMCawJtByRLXASA8iEMJld\nbiX3b7KgOEAnKyHASgt2MxNbdE4fs1Y9orlDgqAWOQKBgQDbqaOHRPCsasiR3fKH\nWw+SbZVq+Cb7KaeIdCzcLq2CShVF3o3lv42bJDxOvktFmvI3TGw7pETd1kUzrODM\n05/iHPCldhpYEOFB9aoKbWyovO314YSUhZl6Ib44xJqkQwyeA6zD6Bd6jWCYR+u/\nfuTosGxpr+3zH7ODVK15tK5KDQKBgQDVPIHwWWj+InvoFsVyPxC5pBDNA2L4qUUZ\nHQ9gjivkqrov0j04ULVfBOPj1nAHqvIsRUvbf88CO8BcRkxEJAKzF22Jx/yKx1Rg\ntpfKPz33CCs9EHYQtFrX+xSOtmjAVV3LjXC9y2IZ5PbS/P8uuCnZgxU7deuozpUB\nKeuq3S2fdwKBgGFfClE9Gx6i2zPl2ctsbzOuhex8AfOWHGCddwFHY7x8kH9/TxFH\n30KlRmJ1cjJxo+slYljx0WEwyU5F1QSWzqnRwE7oUnc1TFULzAuBRAhsb2NuS3H2\n4vjDmmnZpN8ppZ8p69yPtlCp+OaoAvXJDzmicvxKc0UxiUavM5Lep9/FAoGAHHTo\nulSUSGX9tylizC5SYxPcEiADkz+zsvhH1xDiFrAaDMu3084hhj620u8JIFzV2Mae\nqvpRe/DRaP8Qqn9LxO65dYu0zihvwEBd3WW3NUJn0sxhlTUccnpVcf4x2IkL7WBA\nzXNY8i+2KM4OmAOHwjlWGgtQmcSH6hHYG4NM1V0CgYBq2nd10EtF76u3m+fKgJUC\nsfd+W+SQDsjBlbGgiGi3MF7x9xzOrTzX+tp+ne+3baudBAZtaHrdHhkdnjfN4Rz7\n1fzdeXgAVg9/LFQrg1GCit0mcZTb+6MMgoc3ybqO8eEN40HuwawNQfXR+foHMHuA\n4aSS6bfYZ4gYwniIRxA+GQ==\n-----END PRIVATE KEY-----\n"
    GCP_PROJECT_NAME: baobab
    GCP_BUCKET_NAME: fileuploads-deeplearningindaba-staging
    FILE_SIZE_LIMIT: 10485760
    BOABAB_HOST: http://localhost:8080

webapp:
  build: ./webapp
  command: yarn start
  volumes:
    - ./webapp:/usr/src/app
    - ./webapp:/webapp
  ports:
    - "8080:3000"
  environment:
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true
test-ci:
  build: ./webapp
  command: yarn test-ci
  dockerfile: Dockerfile-test
