version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start container
          command: docker-compose up -d
      - run: 
          name: Run migrations
          command: |
            docker-compose run web python api/run.py db upgrade --directory api/migrations
            docker-compose run web python api/run.py db downgrade --directory api/migrations
            docker-compose run web python api/run.py db upgrade --directory api/migrations
      - run:
          name: Run tests
          command: docker-compose run web nosetests -v

  frontEndTests:
    machine: true
    steps:
      - checkout
      - run:
          name: Front-end install and tests.
          command: |
            docker-compose build test-ci 
            docker-compose run test-ci  
  
  deploy:
    docker:
      - image: circleci/node:8 
    steps:
      - checkout
      - run: |
          RUN curl -sSL https://sdk.cloud.google.com | bash
          ENV PATH $PATH:/root/google-cloud-sdk/bin
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          cd webapp
          yarn build
          gcloud app deploy

workflows:
  build_and_test:
    jobs:
      - build
      - frontEndTests
      - deploy

