version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start container
          command: docker-compose up -d
      - run: 
          name: Run migrations
          command: |
            docker-compose run web python api/run.py db upgrade --directory api/migrations
            docker-compose run web python api/run.py db downgrade --directory api/migrations
            docker-compose run web python api/run.py db upgrade --directory api/migrations
      - run:
          name: Run tests
          command: docker-compose run web nosetests -v

  frontEndTests:
    machine: true
    steps:
      - checkout
      - run:
          name: Front-end install and tests.
          command: |
            docker-compose build test-ci 
            docker-compose run test-ci  
  
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          cd webapp
          docker build --rm=false -t us.gcr.io/${GOOGLE_PROJECT_ID}/website:$CIRCLE_SHA1 .
          gcloud docker -- push us.gcr.io/${GOOGLE_PROJECT_ID}/website:$CIRCLE_SHA1
          gcloud compute firewall-rules create allow-http \  --allow tcp:80 --target-tags http-server
          gcloud app deploy --image-url=us.gcr.io/${GOOGLE_PROJECT_ID}/website:$CIRCLE_SHA1 

workflows:
  build_and_test:
    jobs:
      - build
      - frontEndTests
      - deploy

