version: 2.1
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Start container and run tests
          command: |
            docker-compose up -d
      - run: 
          name: Run migrations
          command: |
            docker-compose run web python api/run.py db upgrade --directory api/migrations
            docker-compose run web python api/run.py db downgrade --directory api/migrations
            docker-compose run web python api/run.py db upgrade --directory api/migrations
      - run:
          name: Run tests
            docker-compose run web nosetests -v
