version: 2.1
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Start container
          command: docker-compose up -d
      - run: 
          name: Run migrations
          command: |
            docker-compose run web python api/run.py db upgrade --directory api/migrations
            docker-compose run web python api/run.py db downgrade --directory api/migrations
            docker-compose run web python api/run.py db upgrade --directory api/migrations
      - run:
          name: Run tests
          command: docker-compose run web nosetests -v

  front-end:
    machine: true
    working_directory: ./webapp
    steps:
      - checkout
      - run:
        name: Front-end install and tests.
        command: |
            yarn install
            yarn test
