<<<<<<< HEAD
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /
  static_dir: build
=======
runtime: custom
env: flex
>>>>>>> 06573f2e3312ad54cd36eb6163290c868f4714a1
